# Generated by Django 3.0.4 on 2020-05-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('company_type', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
                ('responsibilities', models.CharField(max_length=25)),
                ('company_location', models.CharField(max_length=35)),
                ('employment_period', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30)),
                ('father_name', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
                ('religion', models.CharField(max_length=10)),
                ('nid', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level_name', models.CharField(max_length=30)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=15)),
                ('year_from', models.DateField(max_length=10)),
                ('year_to', models.DateField(max_length=10)),
                ('institute_name', models.CharField(max_length=30)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.Board')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.EducationLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_app.User')),
            ],
        ),
    ]
